name: Check coverage for PR

on:
  pull_request:

jobs:
  run-tests-check-coverage:
    runs-on: ubuntu-20.04
    name: Run tests & check coverage
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-
      - name: Install Node packages
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Read coverage text report
        uses: fingerprintjs/action-coverage-report-md@v1
        id: coverage-md
        with:
          srcBasePath: './src'
      - name: Jest coverage comment
        id: coverage
        uses: ArtiomTr/jest-coverage-report-action@f1a1382101d9b92b38e3df05c9ed89a834af97c8
        with:
          package-manager: yarn
          output: report-markdown
      - uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56
        with:
          message: |
            ${{ steps.coverage.outputs.report }}
            <details>
              <summary>Show full coverage report</summary>

              ${{ steps.coverage-md.outputs.markdownReport }}
            </details>
