name: Coverage

on:
  push:
    branches:
      - main

jobs:
  build-and-run-tests:
    runs-on: ubuntu-20.04
    name: Build & run tests & publish coverage
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-
      - name: Install Dependencies and prepare packages
        run: yarn install
        env:
          CI: true
      - name: Build
        run: yarn build
      - name: Run test
        run: yarn test

      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@e07f25709cd25486855c1ba1b26da53576ff3620
        with:
          source: coverage/coverage-summary.json
          output: coverage/lcov-report/badges.svg

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc
        with:
          branch: gh-pages
          folder: ./coverage/lcov-report/
