name: E2E test for release

on:
  release:
    types:
      - published

jobs:
  test-release:
    runs-on: ubuntu-24.04
    name: Test release
    steps:
      - uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install pnpm
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Download release asset
        run: node scripts/downloadGitHubRelease.mjs
        env:
          TAG: ${{ github.event.release.tag_name }}

      - name: Generate random paths
        run: |
          postfix=$(date +%s)
          echo WORKER_NAME=automated-test-$postfix >> $GITHUB_OUTPUT
          echo WORKER_PATH=fpjs-worker-$postfix >> $GITHUB_OUTPUT
          echo GET_RESULT_PATH=get-result-$postfix >> $GITHUB_OUTPUT
          echo AGENT_DOWNLOAD_PATH=agent-download-$postfix >> $GITHUB_OUTPUT
        id: random-path-generator
      - name: Modify wrangler.toml
        run: |
           sed -i '/^account_id = ""$/d' wrangler.toml
           sed -i 's/name = .*/name = "${{steps.random-path-generator.outputs.WORKER_NAME}}"/' wrangler.toml
           sed -i 's/route = .*/route = "${{ secrets.TEST_CLIENT_DOMAIN }}\/${{steps.random-path-generator.outputs.WORKER_PATH}}\/*"/' wrangler.toml
           echo [vars] >> wrangler.toml
           echo GET_RESULT_PATH = \"${{ steps.random-path-generator.outputs.GET_RESULT_PATH }}\" >> wrangler.toml
           echo AGENT_SCRIPT_DOWNLOAD_PATH = \"${{ steps.random-path-generator.outputs.AGENT_DOWNLOAD_PATH }}\" >> wrangler.toml
           echo PROXY_SECRET = \"${{secrets.PROXY_SECRET}}\" >> wrangler.toml
           sed -i '/\[build\]/,+1d' wrangler.toml    
           sed -i 's/main = "\.\/dist\/fingerprintjs-pro-cloudflare-worker\.esm\.js"/main = "\.\/fingerprintjs-pro-cloudflare-worker\.esm\.js"/' wrangler.toml
          
           cat wrangler.toml
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8 # commit hash = v0.2.0
        with:
          path: 'package.json'
          prop_path: 'version'
      - name: Install dependencies
        run: pnpm exec playwright install
      - name: Run test
        run:  pnpm test:e2e
        env:
          test_client_domain: ${{secrets.TEST_CLIENT_DOMAIN}}
          worker_version: ${{steps.version.outputs.prop}}
          worker_path: ${{steps.random-path-generator.outputs.WORKER_PATH}}
          get_result_path: ${{ steps.random-path-generator.outputs.GET_RESULT_PATH }}
          agent_download_path: ${{ steps.random-path-generator.outputs.AGENT_DOWNLOAD_PATH }}
      - name: Clean up worker
        run: |
          curl -i -X DELETE "https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/workers/scripts/${{steps.random-path-generator.outputs.WORKER_NAME}}" -H"Authorization: bearer ${{secrets.CF_API_TOKEN}}"
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@0d9c6ff1de9903da88d24c0564f6e83cb28faca9
        with:
          status: ${{ job.status }}
          notification_title: "Cloudflare Worker E2E Release Test has {status_message}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
