name: Test e2e

on:
  pull_request:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  set_datadog_team:
    name: Set Datadog team
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/set-datadog-team.yml@v1
    secrets:
      DD_API_KEY: ${{ secrets.INTEGRATIONS_DATADOG_API_KEY }}

  build-and-deploy-and-test-e2e-mock:
    runs-on: ubuntu-24.04
    name: Build & Deploy & Test e2e using mock app
    strategy:
      max-parallel: 1
      matrix:
        default_compatibility_date:
          - true
          - false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install pnpm
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9

      - name: Upgrade version
        run: |
          pnpm version prerelease --preid snapshot --no-commit-hooks --no-git-tag-version --ignore-scripts

      - name: Install dependencies
        run: pnpm install

      - name: Create the worker script and wrangler.json
        run: |
          pnpm build
          # Remove local wrangler state after build
          rm -rf .wrangler

      - name: Set up the deploy directory
        run: |
          mkdir -p e2e-deploy
          cp dist/*/index.js dist/*/wrangler.json e2e-deploy

      - name: Generate random paths
        run: |
          postfix="$(date +%s)-mock-e2e"
          echo WORKER_NAME=automated-test-$postfix >> $GITHUB_OUTPUT
          echo WORKER_PATH=fpjs-worker-$postfix >> $GITHUB_OUTPUT
          echo GET_RESULT_PATH=get-result-$postfix >> $GITHUB_OUTPUT
          echo AGENT_DOWNLOAD_PATH=agent-download-$postfix >> $GITHUB_OUTPUT
        id: random-path-generator

      - name: Set variables for e2e tests in wrangler.json
        run: |
          jq \
            --arg name "${{steps.random-path-generator.outputs.WORKER_NAME}}" \
            --arg route "${{ secrets.TEST_CLIENT_DOMAIN }}/${{steps.random-path-generator.outputs.WORKER_PATH}}/*" \
            --arg get_result_path "${{ steps.random-path-generator.outputs.GET_RESULT_PATH }}" \
            --arg agent_download_path "${{ steps.random-path-generator.outputs.AGENT_DOWNLOAD_PATH }}" \
            --arg proxy_secret "secret" \
            --arg fpjs_ingress_base_host "${{secrets.MOCK_INGRESS_API}}" \
            '.name = $name | .route = $route | .vars.GET_RESULT_PATH = $get_result_path | .vars.AGENT_SCRIPT_DOWNLOAD_PATH = $agent_download_path | .vars.PROXY_SECRET = $proxy_secret | .vars.FPJS_INGRESS_BASE_HOST = $fpjs_ingress_base_host' \
            e2e-deploy/wrangler.json > e2e-deploy/wrangler.json.tmp && mv e2e-deploy/wrangler.json.tmp e2e-deploy/wrangler.json

      - name: Set compatibility date
        run: |
          [[ "${{ matrix.default_compatibility_date }}" == "true" ]] && compatibility_date="2021-11-02" || compatibility_date="$(date -u +%Y-%m-%d)"
          jq \
            --arg date "$compatibility_date" '.compatibility_date = $date' \
            e2e-deploy/wrangler.json > e2e-deploy/wrangler.json.tmp && mv e2e-deploy/wrangler.json.tmp e2e-deploy/wrangler.json

          cat e2e-deploy/wrangler.json

      - name: Get wrangler version
        id: wrangler-version
        run: echo version=$(pnpm ls --json wrangler | jq -r '.[0].devDependencies.wrangler.version') >> $GITHUB_OUTPUT

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: ${{ steps.wrangler-version.outputs.version }}
          workingDirectory: e2e-deploy
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8 # commit hash = v0.2.0
        with:
          path: 'package.json'
          prop_path: 'version'
      - name: Wait for some time for the worker to come online
        run: sleep 180
        shell: bash
      - name: Run test
        run: |
          npm exec -y "git+https://github.com/fingerprintjs/dx-team-mock-for-proxy-integrations-e2e-tests.git" -- --api-url="${{env.api_url}}" --integration-url="https://${{env.test_client_domain}}/${{env.worker_path}}/" --cdn-path="${{env.agent_download_path}}" --ingress-path="${{env.get_result_path}}" --traffic-name="fingerprintjs-pro-cloudflare" --integration-version="${{steps.version.outputs.prop}}" --enable-new-tests=true
        env:
          test_client_domain: ${{secrets.TEST_CLIENT_DOMAIN}}
          worker_version: ${{steps.version.outputs.prop}}
          worker_path: ${{steps.random-path-generator.outputs.WORKER_PATH}}
          get_result_path: ${{ steps.random-path-generator.outputs.GET_RESULT_PATH }}
          agent_download_path: ${{ steps.random-path-generator.outputs.AGENT_DOWNLOAD_PATH }}
          api_url: https://${{ secrets.MOCK_FPCDN }}
      - name: Clean up worker
        run: |
          curl -i -X DELETE "https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/workers/scripts/${{steps.random-path-generator.outputs.WORKER_NAME}}" -H"Authorization: bearer ${{secrets.CF_API_TOKEN}}"

  build-and-deploy-and-test-e2e:
    runs-on: ubuntu-24.04
    name: Build & Deploy & Test e2e
    strategy:
      max-parallel: 1
      matrix:
        default_compatibility_date:
          - true
          - false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install pnpm
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9

      - name: Upgrade version
        run: |
          pnpm version prerelease --preid snapshot --no-commit-hooks --no-git-tag-version --ignore-scripts

      - name: Install dependencies
        run: pnpm install

      - name: Create the worker script and wrangler.json
        run: |
          pnpm build
          # Remove local wrangler state after build
          rm -rf .wrangler

      - name: Set up the deploy directory
        run: |
          mkdir -p e2e-deploy
          cp dist/*/index.js dist/*/wrangler.json e2e-deploy

      - name: Generate random paths
        run: |
          postfix="$(date +%s)-e2e"
          echo WORKER_NAME=automated-test-$postfix >> $GITHUB_OUTPUT
          echo WORKER_PATH=fpjs-worker-$postfix >> $GITHUB_OUTPUT
          echo GET_RESULT_PATH=get-result-$postfix >> $GITHUB_OUTPUT
          echo AGENT_DOWNLOAD_PATH=agent-download-$postfix >> $GITHUB_OUTPUT
        id: random-path-generator

      - name: Set variables for e2e tests in wrangler.json
        run: |
          jq \
            --arg name "${{steps.random-path-generator.outputs.WORKER_NAME}}" \
            --arg route "${{ secrets.TEST_CLIENT_DOMAIN }}/${{steps.random-path-generator.outputs.WORKER_PATH}}/*" \
            --arg get_result_path "${{ steps.random-path-generator.outputs.GET_RESULT_PATH }}" \
            --arg agent_download_path "${{ steps.random-path-generator.outputs.AGENT_DOWNLOAD_PATH }}" \
            --arg proxy_secret "${{ secrets.PROXY_SECRET }}" \
            '.name = $name | .route = $route | .vars.GET_RESULT_PATH = $get_result_path | .vars.AGENT_SCRIPT_DOWNLOAD_PATH = $agent_download_path | .vars.PROXY_SECRET = $proxy_secret' \
            e2e-deploy/wrangler.json > e2e-deploy/wrangler.json.tmp && mv e2e-deploy/wrangler.json.tmp e2e-deploy/wrangler.json

      - name: Set compatibility date
        run: |
          [[ "${{ matrix.default_compatibility_date }}" == "true" ]] && compatibility_date="2021-11-02" || compatibility_date="$(date -u +%Y-%m-%d)"
          jq \
            --arg date "$compatibility_date" '.compatibility_date = $date' \
            e2e-deploy/wrangler.json > e2e-deploy/wrangler.json.tmp && mv e2e-deploy/wrangler.json.tmp e2e-deploy/wrangler.json

          cat e2e-deploy/wrangler.json

      - name: Get wrangler version
        id: wrangler-version
        run: echo version=$(pnpm ls --json wrangler | jq -r '.[0].devDependencies.wrangler.version') >> $GITHUB_OUTPUT

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: ${{ steps.wrangler-version.outputs.version }}
          workingDirectory: e2e-deploy

      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8 # commit hash = v0.2.0
        with:
          path: 'package.json'
          prop_path: 'version'
      - name: Install playwright dependencies
        run: pnpm exec playwright install
      - name: Run test
        run: pnpm test:e2e
        env:
          test_client_domain: ${{secrets.TEST_CLIENT_DOMAIN}}
          worker_version: ${{steps.version.outputs.prop}}
          worker_path: ${{steps.random-path-generator.outputs.WORKER_PATH}}
          get_result_path: ${{ steps.random-path-generator.outputs.GET_RESULT_PATH }}
          agent_download_path: ${{ steps.random-path-generator.outputs.AGENT_DOWNLOAD_PATH }}
      - name: Clean up worker
        run: |
          curl -i -X DELETE "https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/workers/scripts/${{steps.random-path-generator.outputs.WORKER_NAME}}" -H"Authorization: bearer ${{secrets.CF_API_TOKEN}}"
